project_id = "wiqcfyecdmararxqdmfk"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.telegram-otp]
    verify_jwt = false
  [functions.symptom-checker]
    verify_jwt = false
