project_id = "wiqcfyecdmararxqdmfk"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.telegram-otp]
    verify_jwt = false
  [functions.symptom-checker]
    verify_jwt = false
  [functions.ai-doctor-chat]
    verify_jwt = false
  [functions.ai-report-analysis]
    verify_jwt = false
  [functions.ai-health-risk]
    verify_jwt = false
  [functions.ai-smart-search]
    verify_jwt = false
  [functions.ai-radiology]
    verify_jwt = false
  [functions.medical-knowledge]
    verify_jwt = false
  [functions.ai-health-assistant]
    verify_jwt = false
