// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-knowledge.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { z } from "npm:zod@^3.25.76";
var search_knowledge_default = defineTool({
  name: "search_knowledge",
  title: "Search medical knowledge base",
  description: "Full-text search over MED1.UZ's published medical knowledge articles (Uzbek, Russian, English). Returns title, excerpt, category, language and slug.",
  inputSchema: {
    query: z.string().min(2).describe("Search query (medical term, symptom, disease name)."),
    language: z.enum(["uz", "ru", "en"]).optional().describe("Filter by article language."),
    limit: z.number().int().min(1).max(20).optional().describe("Max results (default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, language, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("knowledge_articles").select("title, excerpt, category, language, slug").eq("published", true).textSearch("search_vector", query, { type: "websearch" }).limit(limit ?? 5);
    if (language) q = q.eq("language", language);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-clinics.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_clinics_default = defineTool2({
  name: "list_clinics",
  title: "List active MED1.UZ clinics",
  description: "List active clinics registered on MED1.UZ, optionally filtered by category or city. Returns name, category, phone, address and specialties.",
  inputSchema: {
    category: z2.string().optional().describe("Filter by clinic category (e.g. dental, diagnostics)."),
    city: z2.string().optional().describe("Case-insensitive substring match on address."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, city, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("registered_clinics_public").select("name, category, phone, address, specialties, website").eq("is_active", true).limit(limit ?? 10);
    if (category) q = q.eq("category", category);
    if (city) q = q.ilike("address", `%${city}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clinics: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Get my MED1.UZ profile",
  description: "Return the signed-in user's MED1.UZ profile (name, phone, address, preferred city). Requires authentication.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("full_name, phone, address, date_of_birth, preferred_city, avatar_url").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [
        { type: "text", text: JSON.stringify({ email: ctx.getUserEmail(), ...data ?? {} }, null, 2) }
      ],
      structuredContent: { email: ctx.getUserEmail(), profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-my-appointments.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_appointments_default = defineTool4({
  name: "list_my_appointments",
  title: "List my MED1.UZ appointments",
  description: "List the signed-in patient's upcoming or past appointments. Requires authentication.",
  inputSchema: {
    status: z3.enum(["pending", "confirmed", "completed", "cancelled"]).optional().describe("Filter by appointment status."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("appointments").select("id, appointment_date, appointment_time, status, total_price, patient_name, notes, clinic_id, doctor_id").eq("patient_id", ctx.getUserId()).order("appointment_date", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wiqcfyecdmararxqdmfk";
var mcp_default = defineMcp({
  name: "med1-uz-mcp",
  title: "MED1.UZ",
  version: "0.1.0",
  instructions: "MED1.UZ tools. Use `search_knowledge` for medical article lookup (public), `list_clinics` to find registered clinics, `get_my_profile` for the signed-in user's MED1.UZ profile, and `list_my_appointments` to review the user's appointments. Authenticated tools act as the signed-in MED1.UZ user under RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_knowledge_default, list_clinics_default, get_my_profile_default, list_my_appointments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
